packages:
  - modules/*
  - packages/*
  - platforms/*
  - sites/*
autoInstallPeers: true
configDependencies:
  "@effected/pnpm-plugin-effect": 0.13.11
  "@savvy-web/pnpm-plugin-silk": 0.48.0
minimumReleaseAgeExclude:
  - "@effected/pnpm-plugin-effect"
  - "@savvy-web/pnpm-plugin-silk"
peerDependencyRules:
  allowedVersions:
    "@savvy-web/rspress-builder>typescript": "6"
    "@savvy-web/bundler>typescript": "6"
