packages:
  - modules/*
  - packages/*
  - platforms/*
  - sites/*
autoInstallPeers: true
configDependencies:
  "@effected/pnpm-plugin-effect": 0.12.0
  "@savvy-web/pnpm-plugin-silk": 0.44.0
overrides:
  "@effect/platform-node@4.0.0-rc.117>@effect/platform-node-shared": 4.0.0-rc.117
peerDependencyRules:
  allowedVersions:
    "@savvy-web/rspress-builder>typescript": "6"
    "@savvy-web/bundler>typescript": "6"
