packages:
  - modules/*
  - packages/*
  - platforms/*
  - sites/*
autoInstallPeers: true
configDependencies:
  "@effected/pnpm-plugin-effect": 0.7.1+sha512-Y6FL3tc/wRtQb1cBsNIUiPVwmfzH+spnl7gNTWyhPeiMdsScPl3McYEiUBoUYPD+eIvdh1QPA1SDDF1YFvrjCg==
  "@savvy-web/pnpm-plugin-silk": 0.34.0+sha512-TUKsRPcu5yf/1A1KzkotloGCp8O3ZwaeKQNIjzuNWPgUt+ocxgTR/EjOyYSPe+ePb3bBraipPdedDfEGkBdCtw==
peerDependencyRules:
  allowedVersions:
    "@savvy-web/rspress-builder>typescript": "6"
    "@savvy-web/bundler>typescript": "6"
