# Generated by pluginfinity. Do not edit.
_PF_TOOLS='Read=view
Bash=bash
Edit=edit
MultiEdit=edit
Write=create
Agent=task
Task=task
Grep=grep
Glob=glob
WebFetch=web_fetch
WebSearch=web_search
Skill=skill'
_PF_TOOLS_PLUGIN='api-docs'
_PF_TOOLS_MCP='{server}-{tool}'
_PF_TOOLS_SERVERS=''
_PF_TOOLS_UNLISTED=unresolved
_PF_HAS_SKILLS='doc-writer plugin-config review rspress-core sync twoslash'
_PF_HAS_AGENTS='rspress-docs'
_PF_HAS_MONITORS=''
_PF_HAS_SERVERS=''
