# Generated by pluginfinity. Do not edit.
_PF_TOOLS=''
_PF_TOOLS_PLUGIN='api-docs'
_PF_TOOLS_MCP='mcp__plugin_{plugin}_{server}__{tool}'
_PF_TOOLS_SERVERS=''
_PF_TOOLS_UNLISTED=keep
_PF_HAS_SKILLS='doc-writer plugin-config review rspress-core sync twoslash'
_PF_HAS_AGENTS='rspress-docs'
_PF_HAS_MONITORS='doc-build-issues'
_PF_HAS_SERVERS=''
